CREATE TABLE IF NOT EXISTS clinics (id SERIAL PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(80) UNIQUE NOT NULL,status VARCHAR(15) NOT NULL DEFAULT 'Activa' CHECK (status IN ('Activa','Suspendida')),plan VARCHAR(40) NOT NULL DEFAULT 'MVP',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS contract_start DATE;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS contract_end DATE;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS billing_status VARCHAR(15) NOT NULL DEFAULT 'Al día' CHECK (billing_status IN ('Al día','Pendiente','Vencida'));
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS contract_notes TEXT NOT NULL DEFAULT '';
INSERT INTO clinics(id,name,slug,status,plan) VALUES(1,'Clínica Integral','clinica-integral','Activa','MVP') ON CONFLICT(id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('clinics','id'),GREATEST((SELECT MAX(id) FROM clinics),1));
CREATE TABLE IF NOT EXISTS app_state (resource VARCHAR(40) PRIMARY KEY,data JSONB NOT NULL DEFAULT '[]'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_by INTEGER);
ALTER TABLE app_state ADD COLUMN IF NOT EXISTS clinic_id INTEGER REFERENCES clinics(id);
UPDATE app_state SET clinic_id=1 WHERE clinic_id IS NULL;
ALTER TABLE app_state ALTER COLUMN clinic_id SET NOT NULL;
ALTER TABLE app_state DROP CONSTRAINT IF EXISTS app_state_pkey;
ALTER TABLE app_state ADD PRIMARY KEY(clinic_id,resource);
CREATE TABLE IF NOT EXISTS auth_users (id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL,password_hash VARCHAR(255) NOT NULL,role VARCHAR(20) NOT NULL CHECK (role IN ('Administrador','Recepción','Profesional')),professional_id INTEGER,status VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK (status IN ('Activo','Inactivo')),last_access TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS clinic_id INTEGER REFERENCES clinics(id);
UPDATE auth_users SET clinic_id=1 WHERE clinic_id IS NULL;
ALTER TABLE auth_users ALTER COLUMN clinic_id SET NOT NULL;
ALTER TABLE auth_users DROP CONSTRAINT IF EXISTS auth_users_email_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_users_clinic_email ON auth_users(clinic_id,lower(email));
CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY,user_id INTEGER REFERENCES auth_users(id),action VARCHAR(80) NOT NULL,resource VARCHAR(40),ip VARCHAR(80),details JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS clinic_id INTEGER REFERENCES clinics(id);
UPDATE audit_log SET clinic_id=1 WHERE clinic_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth_users(lower(email));
CREATE INDEX IF NOT EXISTS idx_app_state_clinic ON app_state(clinic_id);
CREATE TABLE IF NOT EXISTS platform_users (id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,status VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK (status IN ('Activo','Inactivo')),last_access TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS platform_settings (key VARCHAR(80) PRIMARY KEY,value JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO platform_settings(key,value) VALUES('commerce','{"plans":{"MVP":29900,"Profesional":59900,"Premium":99900},"mercadoPago":{"configured":false,"mode":"test","publicKey":"","accessTokenEncrypted":""}}'::jsonb) ON CONFLICT(key) DO NOTHING;
