"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Slot={day:number;start:string;end:string};
type Professional={id:number;name:string;specialty:string;availability?:Slot[];status:string};
type Busy={date:string;time:string;duration:number;professionalId:number};
type BookingData={clinic:{name:string;slug:string};professionals:Professional[];busy:Busy[]};
const toMinutes=(time:string)=>{const[h,m]=time.split(":").map(Number);return h*60+m};
const toTime=(value:number)=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;

export default function PublicBooking(){const[slug,setSlug]=useState(""),[data,setData]=useState<BookingData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState<{date:string;time:string;professional:string}|null>(null),[form,setForm]=useState({professionalId:0,date:"",time:"",name:"",dni:"",phone:"",email:"",reason:"Consulta"});
 useEffect(()=>{const clinic=new URLSearchParams(location.search).get("clinica")||"";setSlug(clinic);if(!clinic){setError("Falta indicar la clínica.");setLoading(false);return}fetch(`/api/public/${clinic}/bootstrap`).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);return body}).then((body:BookingData)=>{setData(body);setForm(x=>({...x,professionalId:body.professionals[0]?.id||0}));setLoading(false)}).catch(e=>{setError(e.message||"No se pudo abrir el turnero");setLoading(false)})},[]);
 const professional=data?.professionals.find(x=>x.id===form.professionalId),dates=useMemo(()=>Array.from({length:21},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i+1);return d}).filter(d=>professional?.availability?.some(x=>x.day===d.getDay())),[professional]),available=useMemo(()=>{if(!professional||!form.date)return[];const day=new Date(`${form.date}T12:00:00`).getDay(),slot=professional.availability?.find(x=>x.day===day);if(!slot)return[];const result:string[]=[];for(let current=toMinutes(slot.start);current+30<=toMinutes(slot.end);current+=30){const time=toTime(current),overlap=data?.busy.some(x=>x.professionalId===professional.id&&x.date===form.date&&current<toMinutes(x.time)+Number(x.duration||30)&&current+30>toMinutes(x.time));if(!overlap)result.push(time)}return result},[data,form.date,professional]);
 const selectProfessional=(id:number)=>setForm(x=>({...x,professionalId:id,date:"",time:""})),selectDate=(date:string)=>setForm(x=>({...x,date,time:""}));
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");try{const response=await fetch(`/api/public/${slug}/appointments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),body=await response.json();if(!response.ok)throw new Error(body.error);setSuccess(body.appointment)}catch(x){setError((x as Error).message)}};
 if(loading)return <main className="public-booking center"><div className="public-loader"><span>✚</span><p>Cargando horarios disponibles…</p></div></main>;
 if(error&&!data)return <main className="public-booking center"><section className="booking-error"><span>✚</span><h1>Turnero no disponible</h1><p>{error}</p></section></main>;
 if(success)return <main className="public-booking center"><section className="booking-success"><span>✓</span><p>RESERVA RECIBIDA</p><h1>Tu turno quedó registrado</h1><div><b>{success.professional}</b><strong>{new Date(`${success.date}T12:00:00`).toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"})} · {success.time}</strong></div><p>La clínica podrá confirmar el turno y enviarte recordatorios por los medios informados.</p><button onClick={()=>location.reload()}>Solicitar otro turno</button></section></main>;
 return <main className="public-booking"><header><div><span>✚</span><div><b>{data?.clinic.name}</b><small>TURNOS ONLINE</small></div></div><p>Reservá tu consulta de forma simple y segura</p></header><form onSubmit={submit}><section className="booking-step"><div className="step-title"><span>1</span><div><h2>Elegí un profesional</h2><p>Seleccioná la especialidad que necesitás.</p></div></div><div className="public-professionals">{data?.professionals.map((x,i)=><button type="button" className={form.professionalId===x.id?"active":""} onClick={()=>selectProfessional(x.id)} key={x.id}><span>{x.name.split(" ").filter(y=>!["Dr.","Dra."].includes(y)).slice(0,2).map(y=>y[0]).join("")}</span><div><b>{x.name}</b><small>{x.specialty}</small></div><i>{form.professionalId===x.id?"✓":"›"}</i></button>)}</div></section><section className="booking-step"><div className="step-title"><span>2</span><div><h2>Seleccioná día y horario</h2><p>Mostramos únicamente turnos disponibles.</p></div></div><div className="public-dates">{dates.map(d=>{const iso=d.toISOString().slice(0,10);return <button type="button" className={form.date===iso?"active":""} onClick={()=>selectDate(iso)} key={iso}><small>{d.toLocaleDateString("es-AR",{weekday:"short"}).replace(".","")}</small><b>{d.getDate()}</b><span>{d.toLocaleDateString("es-AR",{month:"short"}).replace(".","")}</span></button>})}</div>{form.date&&<div className="public-times">{available.map(time=><button type="button" className={form.time===time?"active":""} onClick={()=>setForm(x=>({...x,time}))} key={time}>{time}</button>)}{!available.length&&<p>No quedan horarios disponibles para este día.</p>}</div>}</section><section className="booking-step"><div className="step-title"><span>3</span><div><h2>Completá tus datos</h2><p>La clínica usará esta información para gestionar el turno.</p></div></div><div className="public-fields"><label>Nombre y apellido<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>DNI<input required value={form.dni} onChange={e=>setForm({...form,dni:e.target.value})}/></label><label>WhatsApp / teléfono<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="11 5555 5555"/></label><label>Correo electrónico<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wide">Motivo de consulta<input required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div>{error&&<div className="public-form-error">! {error}</div>}<button className="booking-submit" disabled={!form.professionalId||!form.date||!form.time}>Confirmar solicitud de turno</button><small className="public-privacy">Al continuar autorizás a la clínica a utilizar estos datos para gestionar tu atención.</small></section></form><footer>Turnos administrados por Clínica Integral</footer></main>}
